import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from '../lib/auth';
import styles from '../styles/Home.module.css';

export default function Home() {
  const auth = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Fast Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Fast Feedback</h1>

        <p className={styles.description}>
          <code className={styles.code}>init</code>
        </p>

        {auth?.user ? (
          <>
            <div>Welcome back! {auth?.user?.email}</div>
            <button onClick={(e) => auth.signout()}>Sign Out</button>
          </>
        ) : (
          <>
            <button onClick={(e) => auth.signinWithGithub()}>Sign In</button>
            {/* 인증 사용자 확인은 아래 링크에서. */}
            {/* https://console.firebase.google.com/u/0/project/fast-feedback-demo-b442c/authentication/users?hl=ko */}
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
